name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: main
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:latest
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:tiny
          build-args: |
            "PRELOAD_MODEL=tiny"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:tiny-q5_1
          build-args: |
            "PRELOAD_MODEL=tiny-q5_1"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:base
          build-args: |
            "PRELOAD_MODEL=base"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:base-q5_1
          build-args: |
            "PRELOAD_MODEL=base-q5_1"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:small
          build-args: |
            "PRELOAD_MODEL=small"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:small-q5_1
          build-args: |
            "PRELOAD_MODEL=small-q5_1"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:medium-q5_0
          build-args: |
            "PRELOAD_MODEL=medium-q5_0"
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ftcaplan/matrix-stt-bot:large-q5_0
          build-args: |
            "PRELOAD_MODEL=large-q5_0"